server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: HotelService

  config:
    import:
      - "optional:configserver:http://localhost:8085" 
        
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      deafultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true