server:
  port: 8085


spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hridoyPRGMR/learing-microservice_config
          clone-on-start: true