server:
  port: 8083

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: microservice
  application:
    name: Rating-Service
  config:
    import: optional:file:.env[.properties]

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true